stages:
- build
- deploy

build:
  image: maven:latest
  stage: build
  script: mvn clean package

deploy:
  image: maven:latest
  stage: deploy
  script:
  - HEROKU_API_KEY=$HEROKU_STAGING_API_KEY mvn clean heroku:deploy-war