stages:
#- build
- deploy staging
#
#build:
#  image: maven:latest
#  stage: build
#  script: mvn clean package
#    -

deploy staging:
  image: maven:latest
  stage: deploy staging
  script:
  - HEROKU_API_KEY=$HEROKU_STAGING_API_KEY mvn clean heroku:deploy
  only:
  - master